# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    # docs/conf.py is importing mongoengine
    # so mongoengine needs to be installed as well
    - method: setuptools
      path: .

# Specify the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
