name: MongoengineCI
on:
  # All PR
  pull_request:
  # master branch merge
  push:
    branches:
      - master
  # Manual trigger from Action page
  workflow_dispatch:
  # release tags
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'
env:
  MONGODB_6_0: "6.0"
  MONGODB_7_0: "7.0"

  PYMONGO_4_6: 4.6.3
  PYMONGO_4_7: 4.7.3
  PYMONGO_4_8: 4.8.0
  PYMONGO_4_9: 4.9.1
  PYMONGO_4.10: 4.10.1

  MAIN_PYTHON_VERSION: 3.10

  MONGOSH: 2.2.15 # Needed for MongoDB 6.0+

jobs:
  linting:
    # Run pre-commit (https://pre-commit.com/)
    # which runs pre-configured linter & autoformatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        check-latest: true
    - run: bash .github/workflows/install_ci_python_dep.sh
    - run: pre-commit run -a

  test:
    # Test suite run against recent python versions
    # and against a few combination of MongoDB and pymongo
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", 3.11]
        MONGODB: [$MONGODB_6_0]
        PYMONGO: [$PYMONGO_4_6]
        include:
          - python-version: "3.10"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_6
          - python-version: "3.10"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_6
          - python-version: "3.10"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_7
          - python-version: "3.10"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_8
          - python-version: "3.10"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_9
          - python-version: "3.10"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_7
          - python-version: "3.10"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_7
          - python-version: "3.10"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_8
          - python-version: "3.10"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_9
          - python-version: "3.10"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_10
          - python-version: "3.11"
            MONGODB: $MONGODB_6_0
            PYMONGO: $PYMONGO_4_6
          - python-version: "3.11"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_6
          - python-version: "3.11"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_7
          - python-version: "3.11"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_8
          - python-version: "3.11"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_9
          - python-version: "3.11"
            MONGODB: $MONGODB_7_0
            PYMONGO: $PYMONGO_4_10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
    - name: install mongo and ci dependencies
      run: |
        bash .github/workflows/install_mongo.sh ${{ matrix.MONGODB }}
        bash .github/workflows/install_mongosh.sh ${{ matrix.MONGODB }} ${{ env.MONGOSH }}
        bash .github/workflows/install_ci_python_dep.sh
        bash .github/workflows/start_mongo.sh ${{ matrix.MONGODB }}
    - name: tox dry-run (to pre-install venv)
      run: tox -e $(echo py${{ matrix.python-version }}-mg${{ matrix.PYMONGO }} | tr -d . | sed -e 's/pypypy/pypy/') -- "-k=test_ci_placeholder"
    - name: Run test suite
      run: tox -e $(echo py${{ matrix.python-version }}-mg${{ matrix.PYMONGO }} | tr -d . | sed -e 's/pypypy/pypy/') -- "--cov=mongoengine"
    - name: Send coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github-actions
      if: ${{ matrix.python-version == env.MAIN_PYTHON_VERSION }}
      run: coveralls
